# Generated by Django 4.2.7 on 2023-11-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('headline', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
                ('employment_eligibility', models.CharField(choices=[(1, 'Authorized to work in the US for any employer'), (2, 'Sponsorship required to work in the US'), (0, 'Not specified')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='benefits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
