# Generated by Django 4.2.7 on 2023-11-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userjobtype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='userjobtype',
            name='user',
        ),
        migrations.DeleteModel(
            name='JobType',
        ),
        migrations.DeleteModel(
            name='UserJobType',
        ),
    ]
