# Generated by Django 4.2.7 on 2023-12-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactinformation',
            name='employment_eligibility',
            field=models.IntegerField(choices=[(1, 'Authorized to work in the US for any employer'), (2, 'Sponsorship required to work in the US'), (0, 'Not specified')], max_length=1),
        ),
    ]
