# Generated by Django 4.2.7 on 2023-11-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userjobtype_type_remove_userjobtype_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProgrammingLanguage',
        ),
    ]
