# Generated by Django 4.2.7 on 2023-11-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_resume_delete_programminglanguages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
