# Generated by Django 4.2.7 on 2023-11-14 17:56

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadresume',
            name='resume',
            field=models.FileField(upload_to=accounts.models.slugify_upload),
        ),
        migrations.DeleteModel(
            name='CreateResumeOnIndeed',
        ),
    ]
