# Generated by Django 4.2.7 on 2023-11-29 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_usercontactinformation_uploadjob_benefits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_of_discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_trial', models.IntegerField()),
                ('price', models.FloatField()),
                ('option_description', models.TextField()),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.discount')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paymentoptions')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paymentstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('expiry_date', models.CharField(max_length=5)),
                ('security_code', models.IntegerField()),
                ('name_of_card', models.CharField(max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpaymentcard_address', to='accounts.usercontactinformation')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpaymentcard_city', to='accounts.usercontactinformation')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpaymentcard_country', to='accounts.usercontactinformation')),
                ('postal_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpaymentcard_postal_code', to='accounts.usercontactinformation')),
            ],
        ),
    ]
