# Generated by Django 4.2.7 on 2023-12-06 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('career', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_package', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_of_discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_schedule', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_trial', models.IntegerField()),
                ('price', models.FloatField()),
                ('option_description', models.TextField()),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.discount')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'PaymentStatus',
                'verbose_name_plural': 'PaymentStatus',
            },
        ),
        migrations.CreateModel(
            name='SkillsForJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_skills', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StateJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paymentoption')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paymentstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('expiry_date', models.CharField(max_length=5)),
                ('security_code', models.IntegerField()),
                ('name_of_card', models.CharField(max_length=50)),
                ('payment_default_balance', models.FloatField(blank=True, default=10000, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpaymentcard_address', to='accounts.usercontactinformation')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpaymentcard_city', to='accounts.usercontactinformation')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpaymentcard_country', to='accounts.usercontactinformation')),
                ('postal_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpaymentcard_postal_code', to='accounts.usercontactinformation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadResumeWithFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to=main.models.slugify_upload)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('heard_about_us', models.CharField(choices=[('social media', 'Social Media'), ('mail', 'Mail'), ('search engine', 'Search Engine (Google, Bing, Yahoo)'), ('online video', 'Online Video'), ('newspaper', 'Newspaper'), ('radio', 'Radio'), ('other', 'Other')], max_length=155)),
                ('job_title', models.CharField(max_length=255)),
                ('number_of_employers', models.IntegerField(default=1)),
                ('work_location', models.CharField(choices=[('GNL', 'General Location'), ('RMT', 'Remote'), ('HRD', 'Hybrid Remote'), ('PCS', 'Precise Location')], max_length=255)),
                ('experience_level_for_job', models.CharField(max_length=255)),
                ('salary_min', models.FloatField(blank=True, default=0)),
                ('salary_max', models.FloatField(blank=True, default=100)),
                ('rate_salary', models.CharField(choices=[('PH', 'Per hour'), ('PD', 'Per day'), ('PW', 'Per week'), ('PM', 'Per month'), ('PY', 'Per year')], max_length=255)),
                ('job_description', models.TextField()),
                ('resume_choice', models.CharField(choices=[(1, 'Yes, require a resume'), (2, 'Give the option to include a resume'), (0, "No, don't ask for a resume")], max_length=255)),
                ('benefits', models.CharField(blank=True, max_length=255, null=True)),
                ('job_website', models.URLField(blank=True, null=True)),
                ('person', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (0, 'Unidentified')], null=True)),
                ('compensation_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.compensationpackage')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.industry')),
                ('job_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobschedule')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobtype')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.skillsforjob')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.statejob')),
            ],
        ),
        migrations.CreateModel(
            name='JobCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'This user can create jobs for our website'), (0, "This user can't create jobs for our website")], default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreateResumeOnIndeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_per_hour', models.FloatField()),
                ('experience', models.CharField(choices=[('INT', 'Intern'), ('JNR', 'Junior'), ('MDL', 'Middle'), ('SNR', 'Strong')], max_length=3)),
                ('about', models.TextField()),
                ('programming_languages', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript'), ('csharp', 'C#'), ('cpp', 'C++'), ('ruby', 'Ruby'), ('php', 'PHP'), ('go', 'Go'), ('html', 'HTML'), ('css', 'CSS'), ('typescript', 'TypeScript'), ('dotnet', '.Net')], max_length=20)),
                ('skills', models.CharField(max_length=20)),
                ('frameworks', models.TextField()),
                ('education', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.uploadjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
