# Generated by Django 4.2.7 on 2023-12-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymentcard',
            name='payment_default_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
