# Generated by Django 4.2.7 on 2023-12-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadjob',
            name='resume_choice',
            field=models.CharField(choices=[(1, 'Yes, require a resume'), (2, 'Give the option to include a resume'), (3, "No, don't ask for a resume")], max_length=255),
        ),
    ]
