# Generated by Django 4.2.7 on 2023-12-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userpaymentcard_payment_default_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentcard',
            name='payment_default_balance',
            field=models.FloatField(blank=True, default=10000, null=True),
        ),
    ]
