# Generated by Django 4.2.7 on 2023-12-02 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userpaymentcard_payment_default_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpaymentmodel',
            old_name='payment_amount',
            new_name='payed_amount',
        ),
    ]
