# Generated by Django 4.2.7 on 2023-12-02 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_payment_amount_userpaymentmodel_payed_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentOptions',
            new_name='PaymentOption',
        ),
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'verbose_name': 'PaymentStatus', 'verbose_name_plural': 'PaymentStatus'},
        ),
    ]
